apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: ./apps/podinfo   # путь к твоему чарту в репозитории
      sourceRef:
        kind: GitRepository
        name: flux-demo       # имя GitRepository из clusters/dev/flux-system/gitrepository.yaml
  values:
    replicaCount: 2
    service:
      port: 9898

